Homework sass bem
viktor-beet-root/course-4 pull request #112
Opened 2022-08-16 14:39 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_sass_bem/build/index.html

2022-08-21 20:01 UTC, viktor-beet-root requested changes

2022-08-21 20:01 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_sass_bem/src/css/style.scss
> +@include font-face ('Raleway', normal, 400, '../fonts/raleway-v28-latin-ext-regular');
так у тебе всі шрифти будуть у останню чергу завантажуватись, вони мають бути підключені відразу після міксинів

2022-08-21 20:01 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_sass_bem/src/css/_right_part.scss
> +        font-family: 'Roboto';
якщо це основний шрифт то його задаємо для класу page

2022-09-16 14:43 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_sass_bem/src/css/style.scss
> +@include font-face ('Raleway', normal, 400, '../fonts/raleway-v28-latin-ext-regular');
виправив

2022-09-16 14:44 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_sass_bem/src/css/_right_part.scss
> +        font-family: 'Roboto';
всі заголовки різні, задав для page текст, що в параграфі.

2022-09-18 22:03 UTC, viktor-beet-root requested changes

2022-09-18 22:03 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_sass_bem/src/css/_page-layout.scss
> +    font-family: 'Raleway';
а фолбекі? додати всюди

2022-09-20 14:38 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_sass_bem/src/css/_page-layout.scss
> +    font-family: 'Raleway';
виправив

2022-09-25 22:15 UTC, merged