Homework drop down menu
viktor-beet-root/course-4 pull request #118
Opened 2022-08-20 17:08 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_dropdown_menu/build/index.html

2022-08-21 20:31 UTC, viktor-beet-root requested changes

2022-08-21 20:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_dropdown_menu/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_dropdown_menu/build/index.html
![зображення](https://user-images.githubusercontent.com/73398559/185809620-7099f936-8375-4d6c-bded-f1e83823c740.png)
щось пішло не так

2022-08-21 20:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_dropdown_menu/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_dropdown_menu/build/index.html
![зображення](https://user-images.githubusercontent.com/73398559/185809660-5c3c6fd0-2e40-4459-9e74-67e50d44049b.png)
тут теж
зроби так щоб пункти біль відділялись один від одного хоча б лінію знизу

2022-08-22 12:20 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_dropdown_menu/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_dropdown_menu/build/index.html
виправив

2022-08-28 20:31 UTC, merged