Homework Sidebar
viktor-beet-root/course-4 pull request #120
Opened 2022-08-24 11:57 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_resp_nav/build/index.html

2022-08-28 20:51 UTC, viktor-beet-root requested changes

2022-08-28 20:51 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_resp_nav/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_resp_nav/build/index.html
![зображення](https://user-images.githubusercontent.com/73398559/187093965-e42d1ec9-a7a3-4a07-b728-7e053918fff8.png)
панель меню має бути від верху до низу сторінки 
а тепер спробуй додай якийсь контент на сторінку) чи вийде це в тебе не змінивши стилі

2022-09-16 14:08 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_resp_nav/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_resp_nav/build/index.html
виправив

2022-09-18 22:00 UTC, viktor-beet-root requested changes

2022-09-18 22:00 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_resp_nav/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_resp_nav/build/index.html
![зображення](https://user-images.githubusercontent.com/73398559/190929617-b2a00d4b-1a89-4011-a52f-05fa87d7f910.png)
не зовсім 
тобі не здається що було на багато зручніше це меню зробити position fixed

2022-09-19 20:30 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_resp_nav/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_resp_nav/build/index.html
переробив

2022-09-25 22:12 UTC, merged