Homework js 2 data types
viktor-beet-root/course-4 pull request #135
Opened 2022-09-08 21:10 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/JS-2/index.html

2022-09-12 00:17 UTC, viktor-beet-root requested changes

2022-09-12 00:17 UTC, viktor-beet-root commented on students/samoiliuk_andrii/JS-2/JS/script.js
> +console.log("Number of files: " + Math.floor(fileCount));
в консоль виводимо тільки змінну, виправити скрізь

2022-09-12 00:17 UTC, viktor-beet-root commented on students/samoiliuk_andrii/JS-2/JS/script.js
> +const chocolatePrice = parseFloat(prompt('Task 4. \nWhat is the price of a chocolate', '5')).toFixed(2);
в цій змінній мала бути цифра, а зараз строка, toFixed можна виконати коли формуєш речення для консолі
виправити скрізь

2022-09-16 15:10 UTC, Asamoiliuk commented on students/samoiliuk_andrii/JS-2/JS/script.js
> +console.log("Number of files: " + Math.floor(fileCount));
виправив

2022-09-16 15:10 UTC, Asamoiliuk commented on students/samoiliuk_andrii/JS-2/JS/script.js
> +const chocolatePrice = parseFloat(prompt('Task 4. \nWhat is the price of a chocolate', '5')).toFixed(2);
виправив

2022-09-18 22:06 UTC, viktor-beet-root requested changes

2022-09-18 22:06 UTC, viktor-beet-root commented on students/samoiliuk_andrii/JS-2/JS/script.js
> +const moneyAmount = +prompt('Task 4. Користувач вводить суму грошей в гаманці і ціну однієї шоколадки. Програма виводить скільки шоколадок може купити користувач і скільки здачі у нього залишиться.\n
не треба це все в промт писати забагато тексту
код не має бути довшим за 200 символів
ну і користувачу завдання не потрібно знати він має відповідати на конкретні питання
виправити скрізь

2022-09-20 14:21 UTC, Asamoiliuk commented on students/samoiliuk_andrii/JS-2/JS/script.js
> +const moneyAmount = +prompt('Task 4. Користувач вводить суму грошей в гаманці і ціну однієї шоколадки. Програма виводить скільки шоколадок може купити користувач і скільки здачі у нього залишиться.\n
виправив

2022-09-25 22:14 UTC, merged