Homework13 css position
viktor-beet-root/course-4 pull request #136
Opened 2022-09-09 14:25 UTC by kate-sharko

2022-09-14 20:04 UTC, viktor-beet-root requested changes

2022-09-14 20:04 UTC, viktor-beet-root commented on students/sharko_kateryna/homework13_css_position/readme.md
> +https://kate-sharko.github.io/course-4/students/sharko_kateryna/homework13_css_position/index.html
![зображення](https://user-images.githubusercontent.com/73398559/190251024-02ec229e-c76b-4f1f-b1e9-a382fe4bd580.png)
не працює

2022-09-14 20:04 UTC, viktor-beet-root commented on students/sharko_kateryna/homework13_css_position/readme.md
> +https://kate-sharko.github.io/course-4/students/sharko_kateryna/homework13_css_position/who_using.html
![зображення](https://user-images.githubusercontent.com/73398559/190251213-6e38cee0-c08f-40d8-933b-c56f5e0788be.png)
мабуть треба перевіряти код перед тим як здавати

2022-09-14 20:23 UTC, kate-sharko commented on students/sharko_kateryna/homework13_css_position/readme.md
> +https://kate-sharko.github.io/course-4/students/sharko_kateryna/homework13_css_position/who_using.html
Вторая страница - это задание экстра, его не выполняла - оно не являлось обязательным. Страницу создала, чтоб меню с первой страницы не вело в никуда, так как на макете вторая страница есть.

2022-09-18 21:43 UTC, viktor-beet-root commented on students/sharko_kateryna/homework13_css_position/readme.md
> +https://kate-sharko.github.io/course-4/students/sharko_kateryna/homework13_css_position/who_using.html
![зображення](https://user-images.githubusercontent.com/73398559/190929174-144a6132-f3aa-42db-a3ac-ef41daedc030.png)
це все ще не працює

2022-09-25 21:06 UTC, merged