CV Homework
viktor-beet-root/course-4 pull request #14
Opened 2022-07-25 18:13 UTC by Asamoiliuk

2022-07-25 18:18 UTC, viktor-beet-root requested changes

2022-07-25 18:18 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_CV/about_uk.html
> +</html>
)))))

2022-07-30 21:10 UTC, viktor-beet-root requested changes

2022-07-30 21:10 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_CV/about_uk.html
> +            <h2>Студент курсу Front-End розробки</h2>
h2 не заголовок, це продовження h1
виправити у всіх файлах

2022-07-30 21:10 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_CV/about_uk.html
> +                <li><a href="contacts_uk.html">Контакти</a></li>
в резюме мали бути яконрі посилання

2022-07-30 21:10 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_CV/about_uk.html
> +    <script src="https://kit.fontawesome.com/5aeff80e2f.js" crossorigin="anonymous"></script>
в цьому файлі наскільки бачу іконки не використовуються, тому і підключення не має бути

2022-08-03 13:32 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_CV/about_uk.html
> +            <h2>Студент курсу Front-End розробки</h2>
corrected

2022-08-03 13:32 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_CV/about_uk.html
> +                <li><a href="contacts_uk.html">Контакти</a></li>
corrected

2022-08-03 13:32 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_CV/about_uk.html
> +    <script src="https://kit.fontawesome.com/5aeff80e2f.js" crossorigin="anonymous"></script>
corrected

2022-08-07 19:59 UTC, merged