hw16
viktor-beet-root/course-4 pull request #141
Opened 2022-09-10 18:32 UTC by voichuk1995

2022-09-18 21:01 UTC, viktor-beet-root requested changes

2022-09-18 21:01 UTC, viktor-beet-root commented on students/dergunov_vadim/index.html
> -<!DOCTYPE html>
для чого ти видалив всі ці файли, у тебе є бажанні щоб вони видалились у всіх)))
відновити

2022-09-18 21:01 UTC, viktor-beet-root commented on students/voichuk_serhii/HW_16/readme.md
> +https://voichuk1995.github.io/course-4/students/voichuk_serhii/HW_16/build/
не працює шрифт, або не той шрифт

2022-09-18 21:01 UTC, viktor-beet-root commented on students/voichuk_serhii/HW_16/src/productly.html
> +<!DOCTYPE html>
коли здаєш роботу зайвих файлів не має бути

2022-09-20 07:44 UTC, voichuk1995 commented on students/dergunov_vadim/index.html
> -<!DOCTYPE html>
я робив копію репозиторію починаючи з 16 заняття, і там було вже багато папок інших студетнтів, тому я в себе видалив всіх і лишив тільки сою папку

2022-09-25 22:13 UTC, viktor-beet-root commented on students/dergunov_vadim/index.html
> -<!DOCTYPE html>
потрібно все відновити)

2022-10-05 12:02 UTC, closed without merging