Homework js 3 cycles
viktor-beet-root/course-4 pull request #142
Opened 2022-09-11 19:58 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_js2_cycles/

2022-09-18 21:12 UTC, viktor-beet-root requested changes

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +alert('Сума чисел всіх чисел у проміжку ' + digitOne + '-' + digitTwo + ' = ' + sum);
не використовуй алерт тільки вивід в консоль
і при виводі ні яких операцій, тільки вивід

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    if (digitTwo < digitOne) {
логічно щоб цей іф був першим, а потім вже присвоєння змінних

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +var sum = 0;
що за вар))

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +let digitSix = +prompt("введіть друге число ", "33");
це константи для обчислень створи нові змінні

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    }
цей код можна писати в дві строки

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    array[i] = (digitSeven - digitSeven % (Math.pow(10, i))) / (Math.pow(10, i));
ні ми масиви ще не вчили, тому поки без них

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    console.log(answerTwo + (check * 0.93).toFixed(2));
вже писав при виводі ніяких операцій

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    input = +prompt('введіть число №' + i);
цю змінну правильніше створити в циклі

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    'Неділя']
без масивів

2022-09-18 21:12 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +console.log('Загадане число: ' + n);
користувач за умовою має вводити > <  або =

2022-09-20 13:53 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    array[i] = (digitSeven - digitSeven % (Math.pow(10, i))) / (Math.pow(10, i));
Переписав без масиву. Тепер цикл формує число задом на перед і порівнює його із вихідним

2022-09-20 13:53 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    console.log(answerTwo + (check * 0.93).toFixed(2));
Виправив

2022-09-20 13:53 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +alert('Сума чисел всіх чисел у проміжку ' + digitOne + '-' + digitTwo + ' = ' + sum);
Виправив

2022-09-20 13:53 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    if (digitTwo < digitOne) {
Переробив

2022-09-20 13:53 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +var sum = 0;
Тепер лет

2022-09-20 13:53 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +let digitSix = +prompt("введіть друге число ", "33");
Виправив

2022-09-20 13:54 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    }
Переробив

2022-09-20 13:54 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    input = +prompt('введіть число №' + i);
Переніс

2022-09-20 13:54 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +    'Неділя']
Зробив через switch case

2022-09-20 13:54 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js2_cycles/js/script.js
> +console.log('Загадане число: ' + n);
Зробив

2022-09-25 22:14 UTC, merged