Exam html css
viktor-beet-root/course-4 pull request #157
Opened 2022-09-15 13:11 UTC by Asamoiliuk

2022-10-10 21:43 UTC, viktor-beet-root requested changes

2022-10-10 21:43 UTC, viktor-beet-root commented on students/samoiliuk_andrii/exam_html_css/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/exam_html_css/build/index.html
![изображение](https://user-images.githubusercontent.com/73398559/194955546-8c405ddf-2cae-4d5b-aa19-dfe32b65edfc.png)
присутній горизонтальний скролл

2022-10-10 21:43 UTC, viktor-beet-root commented on students/samoiliuk_andrii/exam_html_css/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/exam_html_css/build/index.html
![изображение](https://user-images.githubusercontent.com/73398559/194955871-69516f3a-b8ee-4d0e-b0e9-f7ce7c459ebc.png)
на мобілі меню не завжди відкривається при кліці на кнопку, особливо це помітно коли клікати ближче до краю

2022-10-10 21:43 UTC, viktor-beet-root commented on students/samoiliuk_andrii/exam_html_css/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/exam_html_css/build/index.html
![изображение](https://user-images.githubusercontent.com/73398559/194956036-9376a6a4-13d5-4932-a620-3d8e1721403e.png)
вся ця зона має бути посилланням

2022-10-10 21:43 UTC, viktor-beet-root commented on students/samoiliuk_andrii/exam_html_css/src/_footer.html
> +            </div>
ні це так не працює, пустих дивів не має бути

2022-10-10 21:43 UTC, viktor-beet-root commented on students/samoiliuk_andrii/exam_html_css/src/_footer.html
> +            </div>
і тут

2022-10-10 21:43 UTC, viktor-beet-root commented on students/samoiliuk_andrii/exam_html_css/src/_header.html
> +                </nav>
щось пішло не так із тегом nav
щось я думаю ти валідатором коду не користувався)

2022-10-10 21:43 UTC, viktor-beet-root commented on students/samoiliuk_andrii/exam_html_css/src/_section1.html
> +<section class="page__section1 section1">
класи краще так не називати section1, краще назвати так щоб це мало зміст peer-to-peer наприклад
а ще може бути клас який би був у всіх секцій

2022-10-21 08:19 UTC, Asamoiliuk commented on students/samoiliuk_andrii/exam_html_css/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/exam_html_css/build/index.html
все виправив

2022-10-21 08:19 UTC, Asamoiliuk commented on students/samoiliuk_andrii/exam_html_css/src/_header.html
> +                </nav>
виправив

2022-10-21 08:55 UTC, Asamoiliuk commented on students/samoiliuk_andrii/exam_html_css/src/_footer.html
> +            </div>
переробив

2022-10-21 08:56 UTC, Asamoiliuk commented on students/samoiliuk_andrii/exam_html_css/src/_footer.html
> +            </div>
і тут

2022-10-21 09:59 UTC, Asamoiliuk commented on students/samoiliuk_andrii/exam_html_css/src/_section1.html
> +<section class="page__section1 section1">
переіменував

2022-10-30 23:38 UTC, merged