Homework js4 functions
viktor-beet-root/course-4 pull request #159
Opened 2022-09-15 18:42 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_js_4_functions/index.html

2022-09-18 21:56 UTC, viktor-beet-root requested changes

2022-09-18 21:56 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +    return arguments.length;
яка умова, прочитай уважно там написано повертати?

2022-09-18 21:56 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +let array = [];
ніяких масивів

2022-09-18 21:56 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +        return "error";
функція не може повернути тобі строку погугли як програмно створити помилку як варіант

2022-09-18 21:56 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +    } else { return "неможливо обчислити" }
так само функція що повертає тип number не може повернути строку

2022-09-18 21:56 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +        return 'error';
те саме, виправити скрізь

2022-09-18 21:56 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +        if (typeof a === 'number' && (isNaN(a) === false) && (a >= 0) && typeof b === 'number' && (isNaN(b) === false) && (b >= 0)) { return a * b; } else { return "error"; }
щось ти тут перемудрив))
isNaN(a) === false це так не працює, ми говорити як перевірити на це значення
ти можеш це прочитати я ні )) якщо хочеш все валідувати створи функцію валідатор, і для неї с декілька функцій))
або валідуй перед тим як викликати цю функцію

2022-09-18 21:56 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +    if (typeof a === 'number' && isNaN(a) === false && a > 0 && a % 1 === 0) {
isNaN(a) === false вже писав
виправити скрізь

2022-09-26 14:17 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +    return arguments.length;
вивів в консоль

2022-09-26 14:17 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +let array = [];
прибрав

2022-09-26 14:17 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +        return "error";
throw

2022-09-26 14:18 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +    } else { return "неможливо обчислити" }
throw

2022-09-26 14:18 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +        return 'error';
throw

2022-09-26 14:19 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +        if (typeof a === 'number' && (isNaN(a) === false) && (a >= 0) && typeof b === 'number' && (isNaN(b) === false) && (b >= 0)) { return a * b; } else { return "error"; }
написав функції isNumber() та isNatural()

2022-09-26 14:19 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_4_functions/js/scrypt.js
> +    if (typeof a === 'number' && isNaN(a) === false && a > 0 && a % 1 === 0) {
!isNan

2022-10-02 23:00 UTC, merged