Homework js 5 objects
viktor-beet-root/course-4 pull request #163
Opened 2022-09-21 21:36 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_js5_objects/

2022-09-25 22:31 UTC, viktor-beet-root requested changes

2022-09-25 22:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +    checkUser: function (name) {
функції які щось перевіряють мають повертати bool тип

2022-09-25 22:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +            let seconds = +this.seconds;
у тебе в об’єкті секунди вже мають правильний тип, приводити треба те що прийшло нове

2022-09-25 22:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +            seconds = seconds + +a;
вище ти перевірив чи є змінна цифрою навіщо ще раз приводити

2022-09-25 22:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +        }
цей метод не потрібний
при зміні секунд перевіряєш скільки  в них хвилин і викликаєш метод що змінить хвилини
при зміні хвилин перевіряєш скільки в них годин і викликаєш метод що змінить години

2022-09-25 22:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +    create: function (nom, denom) {
цього метода не має в умові
по умові ти створюєш об’єкти з дробами і далі викликаєш потрібні методи

2022-09-25 22:31 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +    add: function (dribFirst, dribSecond) {
функція яка додає має виконувати тільки додавання
у тебе має бути окремий метод яких приводить до спільного знаменника

2022-09-27 20:49 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +    checkUser: function (name) {
виправив

2022-09-27 20:49 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +            let seconds = +this.seconds;
переробив

2022-09-27 20:50 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +            seconds = seconds + +a;
переробив

2022-09-27 20:50 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +        }
переробив

2022-09-27 20:50 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +    create: function (nom, denom) {
прибрав

2022-09-27 21:14 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js5_objects/js/script.js
> +    add: function (dribFirst, dribSecond) {
створив окремий метод

2022-10-02 23:05 UTC, merged