Homework js 6 arrays
viktor-beet-root/course-4 pull request #164
Opened 2022-09-23 11:50 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_js6_arrays/index.html

2022-09-25 22:41 UTC, viktor-beet-root requested changes

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
цей метод не підходить хоч і працює) тут потрібен той що нічого не повертає

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
знов не той метод передивитися скрізь

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    console.log(shoppingList);
в програмуванні є один корисний принцип одна функція одна дія))) щось тут пішло не так))
тобі просто потрібен ще був метод що зробить копію масиву і відсортує його так як тобі потрібно
метод що створить строку 
метод що виведе строку

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +function setAsBought(array, name) {
цей метод має скористатися іншим який знайде індекс потрібного продукту, ну а далі просто)

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    let number = array.findIndex(function (element, index, array) {
у тебе має бути метод що шукає індекс

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +function addItem(array, name, price, quantity = 1, units = "шт") {
отримує масив і продукт, тільки два параметра

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
редюс

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
редюс

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +}
вже писав вище) одна функція одна дія))

2022-09-25 22:41 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +        let List = "Відсортований список покупок:\n"
змінна не має називатися з великої літери

2022-09-29 21:22 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
переробив

2022-09-29 21:22 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
переробив

2022-09-29 21:22 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    console.log(shoppingList);
розібрав усе на функції

2022-09-29 21:22 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +function setAsBought(array, name) {
переробив

2022-09-29 21:22 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    let number = array.findIndex(function (element, index, array) {
переробив

2022-09-29 21:23 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +function addItem(array, name, price, quantity = 1, units = "шт") {
ок

2022-09-29 21:23 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
ок

2022-09-29 21:28 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +    array.map(function (element, index, array) {
ок

2022-09-29 21:28 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +}
розбив

2022-09-29 21:28 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js6_arrays/js/script.js
> +        let List = "Відсортований список покупок:\n"
виправив

2022-10-02 23:12 UTC, merged