Homework js classes
viktor-beet-root/course-4 pull request #173
Opened 2022-10-02 19:47 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_js_classes/index.html

2022-10-02 23:30 UTC, viktor-beet-root requested changes

2022-10-02 23:30 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_classes/js/script.js
> +        if (radius > 0 && !isNaN(radius)) { this._radius = radius; } else throw 'wrong type';
ну перевірки зазвичай роблять перед тим як щось зберігають)

2022-10-02 23:30 UTC, viktor-beet-root commented on students/samoiliuk_andrii/homework_js_classes/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_js_classes/index.html
щось пішло не так тисну показати і нічого не відбувається))
натисни на нижню половину кнопки

2022-10-03 15:15 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_classes/js/script.js
> +        if (radius > 0 && !isNaN(radius)) { this._radius = radius; } else throw 'wrong type';
прибрав

2022-10-03 15:15 UTC, Asamoiliuk commented on students/samoiliuk_andrii/homework_js_classes/readme.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/homework_js_classes/index.html
поправив

2022-10-09 21:16 UTC, merged