Exem 2
viktor-beet-root/course-4 pull request #191
Opened 2022-10-21 12:08 UTC by onlyta

2022-10-30 23:39 UTC, viktor-beet-root requested changes
відсуне посилання на гітпайджес

2022-11-09 01:02 UTC, viktor-beet-root requested changes

2022-11-09 01:02 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/readme.md
> +https://onlyta.github.io/course-4/students/dmytrenko_tetiana/menuBurger_scroll/build/index.html
неправильна адреса 
твоя робота лежить по іншому шляху

2022-11-10 14:35 UTC, onlyta commented on students/dmytrenko_tetiana/exem_2/src/readme.md
> +https://onlyta.github.io/course-4/students/dmytrenko_tetiana/menuBurger_scroll/build/index.html
Виправила посилання

2022-11-10 20:19 UTC, viktor-beet-root requested changes

2022-11-10 20:19 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/readme.md
> +https://onlyta.github.io/course-4/students/dmytrenko_tetiana/menuBurger_scroll/build/index.html
посилання не виправлене, завжди перевіряй те що робиш

2022-11-10 21:53 UTC, onlyta commented
Може просто ще не обновилось?

чт, 10 нояб. 2022 г., 21:19 Viktor Dehtiarov ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In students/dmytrenko_tetiana/exem_2/src/readme.md
> <https://github.com/viktor-beet-root/course-4/pull/191#discussion_r1019576024>
> :
>
> > @@ -0,0 +1 @@
>
> +https://onlyta.github.io/course-4/students/dmytrenko_tetiana/menuBurger_scroll/build/index.html
>
> посилання не виправлене, завжди перевіряй те що робиш
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/viktor-beet-root/course-4/pull/191#pullrequestreview-1176438678>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2GC6JL4FBAPIITDBEODLYTWHVKEVANCNFSM6AAAAAARLDNYIE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-11 00:08 UTC, viktor-beet-root requested changes

2022-11-11 00:08 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/readme.md
> +https://onlyta.github.io/course-4/students/dmytrenko_tetiana/menuBurger_scroll/build/index.html
гіт не бреше
![зображення](https://user-images.githubusercontent.com/73398559/201231878-da5c2792-ad6b-4a5e-b56b-c174c4dc247b.png)
ось посилання яке є зараз в файлі readme.md

2022-11-11 09:07 UTC, viktor-beet-root requested changes

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/readme.md
> +https://onlyta.github.io/course-4/students/dmytrenko_tetiana/exem_2/build/index.html
![зображення](https://user-images.githubusercontent.com/73398559/201302369-689a18ba-94fa-47f4-be1c-82d049253307.png)
після заповнення форми сабміт не відбувається

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/readme.md
> +https://onlyta.github.io/course-4/students/dmytrenko_tetiana/exem_2/build/index.html
![зображення](https://user-images.githubusercontent.com/73398559/201302546-0f7784fe-2df2-4cf3-aa21-f2f83fd8d933.png)
карта не працює, потрібно додати гітпайджес в налаштуваннях ключа API

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/index.html
> +    <title>Меню бургер JS edition</title>
щось тут не те

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/index.html
> +    <div class="upButton"></div>
це мав бути тег <a>
краще його розмістити внизу перед закриваючим тегом body

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/index.html
> +        <main class="page">
клас пайдж зазвичай дають тегу body

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/js/script.js
> +"use strict"
use strict тут не потрібен

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/js/script.js
> +import 'slick-carousel';
а для чого тобі слік, якщо ти свайпер використовуєш? 
слайдер має бути тільки один

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/js/script.js
> +    e.preventDefault();
ось тут ти відмінила відправку форми

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/js/script.js
> +    validateElementForm(formElement);
ось перевірила чи вона валідна, 
а відправити не відправила, потрібно подумати як побудувати логіку так щоб все працювало

2022-11-11 09:07 UTC, viktor-beet-root commented on students/dmytrenko_tetiana/exem_2/src/js/script.js
> +const sections = [about, projects, news, gallery, contact];
а не простіше було всім секціям дати один клас і отримати їх за допомогою querySelectorAll

2022-12-15 01:27 UTC, closed without merging