Exam Vue
viktor-beet-root/course-4 pull request #200
Opened 2022-11-20 22:26 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/weather_project/dist/index.html

2022-11-20 23:07 UTC, viktor-beet-root requested changes

2022-11-20 23:07 UTC, viktor-beet-root commented on students/samoiliuk_andrii/weather_project/README.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/weather_project/dist/index.html
зроби дизайн трохи веселіше))

2022-11-25 17:28 UTC, Asamoiliuk commented on students/samoiliuk_andrii/weather_project/README.md
> +https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/weather_project/dist/index.html
додав стилі, роблю респонсів

2022-12-04 22:02 UTC, Asamoiliuk commented
Додав стилі, переробив відображення, зробив респонсів. Спробую ще світлу тему додати

2022-12-15 01:24 UTC, merged