homework#2_cv
viktor-beet-root/course-4 pull request #23
Opened 2022-07-26 18:39 UTC by kseniia15

2022-07-30 21:34 UTC, viktor-beet-root requested changes

2022-07-30 21:34 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/about.html
> +    <title>Document</title>
ой щось ти тут забула)

2022-07-30 21:34 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/about.html
> +                <a href="http://127.0.0.1:5500/students/yakymenko_kseniia/homework1/index.html">
ти хоть пробувала це перевірити на пайджес
це не буде працювати в інтернеті
тут мали бути відносні шляхи

2022-07-30 21:34 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/index.html
> +    <p><a href="#top">Вгору</a></p>
якорні посилання мали бути між сторінками

2022-07-31 19:43 UTC, viktor-beet-root requested changes

2022-07-31 19:43 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/courses.html
> +                <a href="/students/yakymenko_kseniia/homework1/index.html">
неправильні шляхи використвоуй шляхи відносно файлу

2022-07-31 19:43 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/about.html
> +        <h3>Проживаю в Києві</h3>
ти колись бачила загловки без контенту)

2022-07-31 19:43 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/experience.html
> +                інформації.</h3>
це не заголовок

2022-07-31 19:43 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/experience.html
> +                документацією.</h3>
і це

2022-07-31 19:43 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/experience.html
> +                а також робота з договорами та рахунками.</h3>
і це

2022-07-31 20:49 UTC, kseniia15 commented on students/yakymenko_kseniia/homework1/courses.html
> +                <a href="/students/yakymenko_kseniia/homework1/index.html">
В мене працює посилання лише коли адреса починається зі students

2022-08-06 20:47 UTC, viktor-beet-root requested changes

2022-08-06 20:47 UTC, viktor-beet-root commented on students/yakymenko_kseniia/homework1/about.html
> +        <h3>Проживаю в Києві</h3>
не виправлено h2 і h3 це не заголовки, зроби їх абзацами можна взяти в тег strong
це стосується усіх файлів

2022-08-07 21:04 UTC, merged