added home_work1 resume
viktor-beet-root/course-4 pull request #24
Opened 2022-07-26 18:50 UTC by Maryna-Kaliuzhna

2022-07-30 21:38 UTC, viktor-beet-root requested changes

2022-07-30 21:38 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work1/education.html
> +<html lang="en">
і про що ти забула))

2022-07-30 21:38 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work1/education.html
> +    <title>Document</title>
і тут щось забула
виправити у всіх файлах

2022-07-30 21:38 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work1/education.html
> +        <a href="./index.html" rel="next" target="_blank"></a>
цей тег має містити якесь слово і накше його не буде видно

2022-07-31 08:07 UTC, Maryna-Kaliuzhna commented
Доброго дня про який тег ідеться, про цей- html lang="en"? треба "uk".
"цей тег має містити якесь слово і накше його не буде видно" ? А тут я не
зрозуміла , про що  кажеш.

вс, 31 июл. 2022 г. в 00:38, Viktor Dehtiarov ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In students/maryna_kaliuzhna/home_work1/education.html
> <https://github.com/viktor-beet-root/course-4/pull/24#discussion_r933894989>
> :
>
> > @@ -0,0 +1,30 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
>
> і про що ти забула))
> ------------------------------
>
> In students/maryna_kaliuzhna/home_work1/education.html
> <https://github.com/viktor-beet-root/course-4/pull/24#discussion_r933895008>
> :
>
> > @@ -0,0 +1,30 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>Document</title>
>
>
> і тут щось забула
> виправити у всіх файлах
> ------------------------------
>
> In students/maryna_kaliuzhna/home_work1/education.html
> <https://github.com/viktor-beet-root/course-4/pull/24#discussion_r933895059>
> :
>
> > @@ -0,0 +1,30 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>Document</title>
>
> +</head>
>
> +
>
> +<body>
>
> +    <main>
>
> +        <a href="./index.html" rel="next" target="_blank"></a>
>
>
> цей тег має містити якесь слово і накше його не буде видно
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/viktor-beet-root/course-4/pull/24#pullrequestreview-1056494252>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZOU3XNON6L6AUINUMCKJ3DVWWOETANCNFSM54W63RVQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-31 19:44 UTC, viktor-beet-root requested changes

2022-07-31 19:44 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work1/education.html
> +        <a href="./index.html" rel="next" target="_blank"></a>
про це під яким пишу

2022-08-07 17:08 UTC, viktor-beet-root requested changes

2022-08-07 17:08 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work1/README.md
> +https://maryna-kaliuzhna.github.io/course-4/students/maryna_kaliuzhna/home_work1/
посилання не працює

2022-08-07 17:08 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work1/education.html
> +        <a href="./index.html" rel="next" target="_blank"></a>
не виправленно

2022-08-07 17:08 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work1/information.html
> +                <img src="./images/незабутня-подорож-неймовірні-краєвиди.jpg" alt="" width="300">
згадуємо що  я казав про імена файлів

2022-08-07 19:52 UTC, closed without merging