added home_work2 index.html and images
viktor-beet-root/course-4 pull request #25
Opened 2022-07-26 19:04 UTC by Maryna-Kaliuzhna

2022-07-30 21:39 UTC, viktor-beet-root requested changes

2022-07-30 21:39 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work2/index.html
> +<html lang="en">
))))

2022-07-30 21:39 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work2/index.html
> +    <title>Document</title>
)))))

2022-07-31 08:08 UTC, Maryna-Kaliuzhna commented
В першому зауваженні зрозуміла, а у другому ні(((

вс, 31 июл. 2022 г. в 00:40, Viktor Dehtiarov ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In students/maryna_kaliuzhna/home_work2/index.html
> <https://github.com/viktor-beet-root/course-4/pull/25#discussion_r933895249>
> :
>
> > @@ -0,0 +1,94 @@
> +<!DOCTYPE html>
> +<html lang="en">
>
> ))))
> ------------------------------
>
> In students/maryna_kaliuzhna/home_work2/index.html
> <https://github.com/viktor-beet-root/course-4/pull/25#discussion_r933895268>
> :
>
> > @@ -0,0 +1,94 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +
> +<head>
> +    <meta charset="UTF-8">
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +    <title>Document</title>
>
> )))))
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/viktor-beet-root/course-4/pull/25#pullrequestreview-1056494483>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZOU3XIAIC5C6YEARL3HNV3VWWOLLANCNFSM54XADTXA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-31 19:46 UTC, merged