added home_work4_font_fase
viktor-beet-root/course-4 pull request #36
Opened 2022-07-27 21:52 UTC by Maryna-Kaliuzhna

2022-07-31 18:48 UTC, viktor-beet-root requested changes

2022-07-31 18:48 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work4_font_fase/index.html
> +    <title>Home work 4</title>
тут потрібно підлючити шрифти
суть завдання як раз в цьому

2022-07-31 19:03 UTC, Maryna-Kaliuzhna commented
Виправила))Дякую))

вс, 31 июл. 2022 г. в 21:49, Viktor Dehtiarov ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In students/maryna_kaliuzhna/home_work4_font_fase/index.html
> <https://github.com/viktor-beet-root/course-4/pull/36#discussion_r934025325>
> :
>
> > @@ -0,0 +1,89 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>Home work 4</title>
>
>
> тут потрібно підлючити шрифти
> суть завдання як раз в цьому
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/viktor-beet-root/course-4/pull/36#pullrequestreview-1056603527>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZOU3XJWPPTRKBQO66SDTM3VW3DBZANCNFSM543DZY6Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-07 17:10 UTC, viktor-beet-root requested changes

2022-08-07 17:10 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work4_font_fase/README.md
> +https://maryna-kaliuzhna.github.io/course-4/students/maryna_kaliuzhna/home_work4_font_fase/
посилання не працює

2022-08-07 17:10 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work4_font_fase/index.html
> +    <title>Font Fase</title>
зміст цієї роботи у підключенні шрифтів
а їх тут немає

2022-08-07 21:11 UTC, viktor-beet-root requested changes

2022-08-07 21:11 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work4_font_fase/css/style.css
> +         url('./fonts/pt-sans-v17-latin-ext_latin-regular.svg#PTSans') format('svg'); /* Legacy iOS */
ми вже не використовуємо це вже засторіло

2022-08-07 21:11 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work4_font_fase/index.html
> +    <link rel="stylesheet" href="./css/fonts/staatliches-v11-latin-ext_latin-regular.woff2">
що це?

2022-08-07 21:11 UTC, viktor-beet-root commented on students/maryna_kaliuzhna/home_work4_font_fase/README.md
> +https://maryna-kaliuzhna.github.io/course-4//students/maryna_kaliuzhna/home_work4_font_fase/index.html
щось пішло не так
![изображение](https://user-images.githubusercontent.com/73398559/183311133-10f0a65a-612e-4916-bf0a-dbd6edde6d47.png)

2022-08-21 19:49 UTC, merged