Lesson 8 homework forms
viktor-beet-root/course-4 pull request #44
Opened 2022-07-29 13:54 UTC by Asamoiliuk

2022-07-31 19:13 UTC, viktor-beet-root requested changes

2022-07-31 19:13 UTC, viktor-beet-root commented on students/samoiliuk_andrii/Lesson_8_homework_forms/style.css
> +    box-sizing: border-box;
це пагана ідея)

2022-07-31 19:13 UTC, viktor-beet-root commented on students/samoiliuk_andrii/Lesson_8_homework_forms/index.html
> +            <form action="./index.html" method="post" target="_blank" autocomplete="on">
autocomplete="on" начення on задавати не потрібно, воно і так за замовчуванням увімкненно

2022-07-31 19:13 UTC, viktor-beet-root commented on students/samoiliuk_andrii/Lesson_8_homework_forms/index.html
> +                    <input id="submit" type="submit" value="Sign Up" class="button">
використовуй тег button

2022-07-31 19:13 UTC, viktor-beet-root commented on students/samoiliuk_andrii/Lesson_8_homework_forms/style.css
> +    margin-left: 3px !important;
я вже казав про іпотента)))

2022-08-14 09:56 UTC, Asamoiliuk commented on students/samoiliuk_andrii/Lesson_8_homework_forms/style.css
> +    box-sizing: border-box;
переніс лише до тих селекторів де це необхідно

2022-08-14 09:56 UTC, Asamoiliuk commented on students/samoiliuk_andrii/Lesson_8_homework_forms/index.html
> +            <form action="./index.html" method="post" target="_blank" autocomplete="on">
видалив

2022-08-14 09:57 UTC, Asamoiliuk commented on students/samoiliuk_andrii/Lesson_8_homework_forms/index.html
> +                    <input id="submit" type="submit" value="Sign Up" class="button">
переробив всі кнопки на цей тег

2022-08-14 09:57 UTC, Asamoiliuk commented on students/samoiliuk_andrii/Lesson_8_homework_forms/style.css
> +    margin-left: 3px !important;
і без нього працює))

2022-08-21 19:35 UTC, merged