Homework8 html form
viktor-beet-root/course-4 pull request #47
Opened 2022-07-29 21:25 UTC by kate-sharko

2022-07-31 19:17 UTC, viktor-beet-root requested changes
додай посилання на гітпайджес

2022-07-31 20:22 UTC, kate-sharko commented
https://kate-sharko.github.io/course-4/students/sharko_kateryna/homework8_html_form/index.html

2022-08-06 20:37 UTC, viktor-beet-root requested changes

2022-08-06 20:37 UTC, viktor-beet-root commented on students/sharko_kateryna/homework8_html_form/profile.html
> +    <div>
це просто елементи форми, а не форма,
загадай як ми на уроці створювали форму)
(все має бути в тезі форми)

2022-08-06 20:37 UTC, viktor-beet-root commented on students/sharko_kateryna/homework8_html_form/profile.html
> +        <input type="file">
у елементів відсутній атрибут name 
прочитати про значення цього атрибуту

2022-08-06 20:37 UTC, viktor-beet-root commented on students/sharko_kateryna/homework8_html_form/profile.html
> +        </div>
класти лейбу в окремий div не має сенсу

2022-08-08 11:42 UTC, kate-sharko commented on students/sharko_kateryna/homework8_html_form/profile.html
> +        </div>
На этом уроке мы ещё не проходили CSS, сделала label в div чтоб стал блочным элементом и текст располагался над формой как на макете, а не в строку

2022-08-18 23:22 UTC, viktor-beet-root requested changes

2022-08-18 23:22 UTC, viktor-beet-root commented on students/sharko_kateryna/homework8_html_form/profile.html
> +        </div>
лейба не має лежати в окремому div тезі))

2022-08-21 20:20 UTC, viktor-beet-root requested changes

2022-08-21 20:20 UTC, viktor-beet-root commented on students/sharko_kateryna/homework8_html_form/readme.md
> +https://kate-sharko.github.io/course-4/students/sharko_kateryna/homework8_html_form/index.html
а на іншу сторінку?

2022-08-21 20:20 UTC, viktor-beet-root commented on students/sharko_kateryna/homework8_html_form/profile.html
> +        </div>
в лейбі не має бути параграфу

2022-08-28 20:32 UTC, merged