Homework css weather forecast
viktor-beet-root/course-4 pull request #73
Opened 2022-08-04 11:25 UTC by Asamoiliuk

Link to pages:

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/weather_forecast/index.html

2022-08-07 20:23 UTC, viktor-beet-root requested changes

2022-08-07 20:23 UTC, viktor-beet-root commented on students/samoiliuk_andrii/weather_forecast/css/style.css
> +    font-family: "Lucida Sans Unicode";
тут ще щось має бути), на випадок якщо цей шрифт зафейлится

2022-08-08 15:15 UTC, Asamoiliuk commented on students/samoiliuk_andrii/weather_forecast/css/style.css
> +    font-family: "Lucida Sans Unicode";
виправив

2022-08-18 23:27 UTC, viktor-beet-root requested changes

2022-08-18 23:27 UTC, viktor-beet-root commented on students/samoiliuk_andrii/weather_forecast/index.html
> +            <li class="w50">
всі тегі мають мати одні і ті ж класи, у тебе є псевдо класи які дозволять розставити все як на макеті

2022-08-20 13:12 UTC, Asamoiliuk commented on students/samoiliuk_andrii/weather_forecast/index.html
> +            <li class="w50">
переробив

2022-08-21 20:27 UTC, viktor-beet-root requested changes

2022-08-21 20:27 UTC, viktor-beet-root commented on students/samoiliuk_andrii/weather_forecast/css/style.css
> +    src: url("./lucida_sans_unicode.ttf");
тут явно чогось не вистачає)

2022-09-16 14:30 UTC, Asamoiliuk commented on students/samoiliuk_andrii/weather_forecast/css/style.css
> +    src: url("./lucida_sans_unicode.ttf");
додав

2022-09-18 22:01 UTC, merged