Lesson 9 homework novik css
viktor-beet-root/course-4 pull request #76
Opened 2022-08-04 14:00 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/lesson_9_homework_novik_css/index.html

2022-08-07 20:33 UTC, viktor-beet-root requested changes

2022-08-07 20:33 UTC, viktor-beet-root commented on students/samoiliuk_andrii/lesson_9_homework_novik_css/css/style.css
> +    font-family: 'Open Sans', sans-serif;
додай ще резервних шрифтів

2022-08-07 20:33 UTC, viktor-beet-root commented on students/samoiliuk_andrii/lesson_9_homework_novik_css/css/style.css
> +    max-width: 970px;
ширину обмежують контейнеру, а не цім елементам

2022-08-09 13:27 UTC, Asamoiliuk commented on students/samoiliuk_andrii/lesson_9_homework_novik_css/css/style.css
> +    max-width: 970px;
додав блок контейнер

2022-08-09 13:27 UTC, Asamoiliuk commented on students/samoiliuk_andrii/lesson_9_homework_novik_css/css/style.css
> +    font-family: 'Open Sans', sans-serif;
додав

2022-08-18 23:32 UTC, merged