Lesson 11 homework productly float
viktor-beet-root/course-4 pull request #87
Opened 2022-08-06 19:16 UTC by Asamoiliuk

https://asamoiliuk.github.io/course-4/students/samoiliuk_andrii/Lesson_11_homework_productly_float/index.html

2022-08-07 21:03 UTC, viktor-beet-root requested changes

2022-08-07 21:03 UTC, viktor-beet-root commented on students/samoiliuk_andrii/Lesson_11_homework_productly_float/css/style.css
> +    /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
видали ці коменти вони не потрібні

2022-08-07 21:03 UTC, viktor-beet-root commented on students/samoiliuk_andrii/Lesson_11_homework_productly_float/css/style.css
> +    font-family: 'Poppins', Arial, Helvetica, sans-serif;
а для слідуючого заголовку знов будеш окремо шрифт вказувати
створи класс для всіх заголовків і вкажи йому шрифт

2022-08-14 10:36 UTC, Asamoiliuk commented on students/samoiliuk_andrii/Lesson_11_homework_productly_float/css/style.css
> +    /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
видалив

2022-08-14 10:38 UTC, Asamoiliuk commented on students/samoiliuk_andrii/Lesson_11_homework_productly_float/css/style.css
> +    font-family: 'Poppins', Arial, Helvetica, sans-serif;
це не заголовок а кнопка, яка далі зустрічається ще декілька разі, в неї власний шрифт. переіменував клас в .button

2022-08-21 19:36 UTC, merged